### ISSUE TITLE
Unable to start program 'C:\Source\source-sdk-2013-ce\sp\src\game\client\.\Debug_mod_sdk2013ce\client.dll'.

### ISSUE THREAD

**Issue by chaziz94** [Nbc66/source-sdk-2013-ce#10]
![image](https://user-images.githubusercontent.com/45898787/128651514-e5006a27-1abb-49c6-974f-2a17b24625bc.png)

Why is it trying to open a "DLL file" from a non-existent directory that cannot be created?

It worked 7 months ago with the original Valve Source SDK 2013 code. And now it doesn't work on both the original Valve version and the Community Edition version.

Everything compiles, but it's straight up exporting it into a black hole.

**Comment by chaziz94** [comment]
update: forgot you had to launch the sourcemod via steam lmao

**Comment by Derailedzack** [comment]
That or you could change the application that visual studio opens when running it through visual studio
