### ISSUE TITLE
[Suggestion] Localization support for binding key names

### ISSUE THREAD

**Issue by Blueberryy** [Nbc66/source-sdk-2013-ce#14]
I'm not a dev but it would be awesome if someone make all binding names localized. https://github.com/Nbc66/source-sdk-2013-ce/blob/34bc1c2a8810c273614618c9a45621a59ed3da1d/mp/game/mod_hl2mp/scripts/kb_keys.lst
By "localized" i mean translating support for other languages like Spanish and etc.

**Comment by Nbc66** [comment]
they allready are
