### ISSUE TITLE
Ammo doesn't work

### ISSUE THREAD

**Issue by PatchByte** [Nbc66/source-sdk-2013-ce#21]
`givecurrentammo` does not work!
`Ammo Pickups`does not work!
I tried to figure out what the problem is according to the internet it has to do something with skill.cfg?

**Comment by Nbc66** [comment]
skd2013's episodic game folder is missing the skill cfg you can take the one from the hl2_mod folder and use it

**Comment by PatchByte** [comment]
ah ok thanks 👍
