### ISSUE TITLE
batch files don't create Everything.sln VS2019

### ISSUE THREAD

**Issue by CodingGardian** [Nbc66/source-sdk-2013-ce#25]
Good evening,
I've installed MFC, Windows 11 SDK 10.0.20000.0 and Visual studio 2019, but when I try to run the batch files they throw an error saying: Unable to find RegKey for .vcproj or .vcxproj files in solutions.

I've tried reinstalling source-sdk-2013-ce and the MFC v142 build tools with no luck.

Below I've attached the error message and the optional libraries I have installed with Visual Studio 2019
![a1](https://user-images.githubusercontent.com/62391363/177875939-9c442fc1-ce39-437f-a0ce-d9beaa85d316.png)
![a2](https://user-images.githubusercontent.com/62391363/177875943-7dacb97d-f5ac-42c1-9940-f7ed29d72d0b.png)

**Comment by DotWith** [comment]
Dup of #15.
Fix can be found [here](https://developer.valvesoftware.com/wiki/Source_SDK_2013#Unable_to_find_RegKey_for_.vcproj_files_in_solutions_.28Windows.29)

**Comment by CodingGardian** [comment]
The fix on the valve website is different than my computer
![a3](https://user-images.githubusercontent.com/62391363/177890067-e12a8e00-6111-41c5-8f60-5595593d13d6.png)

**Comment by CodingGardian** [comment]
Fixed, apologies for the inconvenience
