### ISSUE TITLE
full list of issues i found

### ISSUE THREAD

**Issue by breakdowngamesYT** [Nbc66/source-sdk-2013-ce#31]
props wood boards crates esc are unbreakable with any weapons, npcs will die in the middle of an action, all npcs die in one hit with all wepaons, ammo and health pickups think you are always full heath and ammo (even at no ammo), and ya im using source sdk 2013 upcoming visual studio 2022 with Windows SDK 10.0.22000.0, Multibyte MFC Library and v142 build tools on windows 10

**Comment by AnthonyPython** [comment]
sounds like some file problems, so far with a proper mod none of these are reproducable. double check your files.

**Comment by breakdowngamesYT** [comment]
i had all theses issues with the vaulve repo of source sdk 2013 and iv reset my pc and tried visual studio 2019 i dont think its on my end
