### ISSUE TITLE
[ENCHCEMENT] Jolt

### ISSUE THREAD

**Issue by DotWith** [Nbc66/source-sdk-2013-ce#35]
### [Repo](https://github.com/Joshua-Ashton/VPhysics-Jolt)
An open-source replacement of **VPhyiscs**.

# The Features it brings (Stole it from the readme)
| Feature       | VPhysics | Volt (VPhysics Jolt) | Bullet VPhysics |
|:--------------|:--------:|:-------------:|:---------------:|
| Constraints (except Pulleys)                                  | ✔️ | ✔️ | ✔️ |
| Pulleys                                                       | ✔️ | ❌ | ❌ |
| Breakable constraints                                         | ✔️ | ❌ | ❌ |
| Motors (Motion Controllers)                                   | ✔️ | ✔️ | ✔️ |
| Motors (Constraint)                                           | ✔️ | ✔️ | ❌ |
| Ragdolls                                                      | ✔️ | ✔️ (some bugs) | ✔️ |
| Triggers                                                      | ✔️ | ✔️ | ❌ |
| Object touch callbacks                                        | ✔️ | ✔️ | ❌ |
| Prop damage/breaking                                          | ✔️ | ✔️ | ❌ |
| Fluid events                                                  | ✔️ | ✔️ | ❌ |
| Prop splashing effects                                        | ✔️ | ✔️ | ❌ |
| Wheeled Vehicles                                              | ✔️ | ✔️ | ✔️ |
| Raycast Vehicles (ie. Airboat)                                | ✔️ | ❌ | 〰️ (janky) |
| NPCs/Doors (Shadow Controllers)                               | ✔️ | ✔️ | ✔️ |
| Save/Restore Support                                          | ✔️ | ✔️ | ❌ |
| Portal Support                                                | ✔️ | ✔️ | ❌ |
| Game per-object collide callback support<br>eg. no-collide    | ✔️ | ✔️ | ❌ |
| Crash-resistant solver                                        | ❌ | ✔️ | (no data) |
| Supports thousands of objects without lag                     | ❌ | ✔️ | ❌ |
| Multithreaded                                                 | ❌ | ✔️ | ✔️ (partially) |
| Proper player controller                                      | ✔️ | ❌ (needs work!) | ✔️ (partially) |

**Comment by Nbc66** [comment]
We were allredy testing volt on another game so far we will wait untill all the features are ironed out then we will procede with adding in jolt to rhw base of sdk2013ce

**Comment by Guidealorean** [comment]
make jolt optional please
we may like good physics but we laugh at the most stupid stuff ever so we also like janky physics

**Comment by DotWith** [comment]
@Guidealorean It will be optional as we can't force you replace the physics in the engine bin.

**Comment by breakdowngamesYT** [comment]
if im correct jolt has ended development

**Comment by DotWith** [comment]
> if im correct jolt has ended development

No, neither Jolt nor Volt have ended development. Both projects were updated this week.

**Comment by breakdowngamesYT** [comment]
jolt is volt

**Comment by Headofacrab** [comment]
> jolt is volt

Yea but Volt is a modified version of jolt but made to work with Source Engine and "optimized" for it's use case

**Comment by Nbc66** [comment]
Jolt is still wip untill its finished we won't consider it
