### ISSUE TITLE
_msize_base': redefinition; different exception specifications

### ISSUE THREAD

**Issue by brannanz** [Nbc66/source-sdk-2013-ce#36]
When I attempt to compile the multiplayer version, I get this error.

Error	C2382	'_msize_base': redefinition; different exception specifications
in
memoverride.cpp

### Steps to Reproduce

Create multiplayer game projects
Change solution settings to release
Rebuild solution

![image](https://user-images.githubusercontent.com/76947244/196675436-c09c6129-da0c-4bb0-a468-8cc235f43775.png)

### Operating System

Windows 10

I should also say, that upon removing noexcept from line 281 in memoverride, the game compiles but upon map load the game crashes. That could just be on my end though.

Update: Forgot to place info_player_starts. Forget the map loading stuff! Sorry!

**Comment by Nbc66** [comment]
You didn't download the needed windows sdk for 2013ce its stated in the readme page

**Comment by brannanz** [comment]
I already had that

**Comment by craftablescience** [comment]
add `_CRT_NOEXCEPT` to the end of the `_msize_base` function signature

**Comment by AnthonyPython** [comment]
the function already has the requried end for that function signature,
please check that the projects are using the right windows sdk, just because you have it doesn't mean it is using it.

**Comment by craftablescience** [comment]
Thank you for the downvote, that does fix it on more modern versions of the windows SDK however
