### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by breakdowngamesYT** [Nbc66/source-sdk-2013-ce#37]
### Expected Behavior

it should open the main menu

### Steps to Reproduce

1.compile code in release mode
2.open mod
3.infinemt loading

### Detailed Description

i just sit in the loading screen only in my mod others run fine

### Operating System

windows 11

**Comment by AnthonyPython** [comment]
I can't test on win 11, how ever make sure you are using episodic files and not just base hl2 since we use the episodic code base.
