### ISSUE TITLE
ERROR: Unable to find RegKey for vcproj or vcxproj files.

### ISSUE THREAD

**Issue by soyfeo123** [Nbc66/source-sdk-2013-ce#41]
### Expected Behavior

it should make the sln files in vs2019.

### Steps to Reproduce

1. run createallprojects.bat/creategameprojects.bat with vs2019

### Detailed Description

it does everything correctly, but at the end it makes that error.

### Operating System

Windows 11

**Comment by craftablescience** [comment]
https://github.com/ValveSoftware/source-sdk-2013/issues/72#issuecomment-20557677

**Comment by soyfeo123** [comment]
it doesn't help

**Comment by soyfeo123** [comment]
i don't feel comfortable changing registry keys on my own

**Comment by craftablescience** [comment]
You'll have to, since its impossible to fix vpc without source code

**Comment by illegitimate-egg** [comment]
I edited the registry to all vcproj and now, unsurprisingly it doesn't detect vcxproj
