### ISSUE TITLE
MP Fail to Work

### ISSUE THREAD

**Issue by derric-young** [Nbc66/source-sdk-2013-ce#43]
### Expected Behavior

Work like How Singleplayer Builds. why does MP not?

### Steps to Reproduce

After Building on any Ordernary Setup. set it up in a source mod and there. error

### Detailed Description

assert error line 618.

### Operating System

Windows

**Comment by Nbc66** [comment]
these are mainly issues if you compile in debug and run the game without a debugger attached to the hl2.exe 

if you could provide a crash dump or the location of the crash like in which file the assert happened i can check it out

**Comment by Derailedzack** [comment]
From tier1\utlbuffer.cpp
```c++
//-----------------------------------------------------------------------------
// Reads a null-terminated string
//-----------------------------------------------------------------------------
void CUtlBuffer::GetStringInternal( char *pString, size_t maxLenInChars )
{
	if ( !IsValid() )
	{
		*pString = 0;
		return;
	}

	Assert( maxLenInChars != 0 );

	if ( maxLenInChars == 0 )
	{
		return;
	}

	// Remember, this *includes* the null character
	// It will be 0, however, if the buffer is empty.
	int nLen = PeekStringLength();

	if ( IsText() )
	{
		EatWhiteSpace();
	}

	if ( nLen <= 0 )
	{
		*pString = 0;
		m_Error |= GET_OVERFLOW;
		return;
	}

	const size_t nCharsToRead = min( (size_t)nLen, maxLenInChars ) - 1;

	Get( pString, nCharsToRead );
	pString[nCharsToRead] = 0;

	if ( (size_t)nLen > (nCharsToRead + 1) )
	{
		SeekGet( SEEK_CURRENT, nLen - (nCharsToRead + 1) );
	}

	// Read the terminating NULL in binary formats
	if ( !IsText() )
	{
		VerifyEquals( GetChar(), 0 );
	}
}

```

**Comment by Derailedzack** [comment]
If you want I can include a screenshot of the debugger.

**Comment by derric-young** [comment]
Ok. Did not expect a response after it being closed Sent from Mail for Windows From: GhostfreddySent: Sunday, 4 June 2023 2:50 PMTo: Nbc66/source-sdk-2013-ceCc: derric-young; AuthorSubject: Re: [Nbc66/source-sdk-2013-ce] MP Fail to Work (Issue #43) If you want I can include a screenshot of the debugger.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Derailedzack** [comment]
![windbg_nD0wXFUVER](https://github.com/Nbc66/source-sdk-2013-ce/assets/36719411/70eceda0-5944-4e27-91bb-c49d2f47f3a7)
![windbg_UKVlPvDV8p](https://github.com/Nbc66/source-sdk-2013-ce/assets/36719411/995b6449-0136-484f-a8df-bfe4fe573401)

**Comment by Derailedzack** [comment]
Removing the assert only seems to mess up the text on the title screen

**Comment by derric-young** [comment]
weird Sent from Mail for Windows From: GhostfreddySent: Sunday, 4 June 2023 4:36 PMTo: Nbc66/source-sdk-2013-ceCc: derric-young; AuthorSubject: Re: [Nbc66/source-sdk-2013-ce] MP Fail to Work (Issue #43) Removing the assert only seems to mess up the text on the title screen—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Derailedzack** [comment]
Why is maxLenInChars NULL?

**Comment by Derailedzack** [comment]
Why does this function do a not null check?

**Comment by Derailedzack** [comment]
CUtlBuffer::GetStringInternal is only in the mp source
