### ISSUE TITLE
Bat files are not making sln files

### ISSUE THREAD

**Issue by Headofacrab** [Nbc66/source-sdk-2013-ce#45]
### Expected Behavior

When click on the bat file (both the all and game projects) make the sln files it doesn't WORK .

### Steps to Reproduce

1. you open the batch files 
2.  do it's says building vs 2013 even when vs2019 is installed and I tried vs 2013 and then it says building partial dependencies 
3. it closes right after

### Detailed Description

It doesn't make SLN files

### Operating System

Windows 11 22h2

**Comment by Headofacrab** [comment]
Thank you

**Comment by Nbc66** [comment]
If the issue has been resolved on youre end pls close this issue

Thank you
