### ISSUE TITLE
Visual Studio recompiles entire soultion

### ISSUE THREAD

**Issue by SaggyBlackSack** [Nbc66/source-sdk-2013-ce#5]
Despite /MP /Z* and all sorts of header resource checks every standard build will get a 
"Forcing rebuild of all source files due to a change in the command line since the last build"

**Comment by SaggyBlackSack** [comment]
Although, I have gotten this base working using vs2017 
Issue was with vs2013 using MP in conj with GM means multi core doesn't work for some reason. Not the case on visual studio 2017. Perfect launch into game
Ian fam you got fat are you alrightyy my guyy

**Comment by illegitimate-egg** [comment]
bruh
