### ISSUE TITLE
i need help getting MSVC v143 VS 2022 C++ for VS 2019 CE

### ISSUE THREAD

**Issue by king-of-cheese** [Nbc66/source-sdk-2013-ce#50]
### Expected Behavior

i cant find MSVC v143 VS 2022 C++ when installing VS 2019 sdk. i couldnt find anything for the issue that would fit this problem other that "bug"

### Steps to Reproduce

i have to do this so i can submit this.

### Detailed Description

i just cant find MSVC v143 VS 2022 C++

### Operating System

Windows

**Comment by valberrie** [comment]
The v143 Build Tools are not available for Visual Studio 2019. They are available on Visual Studio 2022.
