### ISSUE TITLE
Tripmine doesn't explode when the object it attached to got destroyed.

### ISSUE THREAD

**Issue by n2g7mutf8** [Nbc66/source-sdk-2013-ce#53]
### Expected Behavior

The tripmine should explode when the object it attached to moved or destroyed.

### Steps to Reproduce

1. Load in the map dm_lockdown
2. Set sv_cheats to 1
3. Use impulse 101 to get all in game item
4. Find either a sink or a toilet in the map.
5. Crouch and place the tripmine angle toward the floor.
6. Moveout use crossbow or .357 to destroy the attached object.
7. The tripmine should be floating in the air.

### Detailed Description

Video: https://streamable.com/2umsjp

### Operating System

Windows 10

**Comment by Nbc66** [comment]
we do not fix game code bugs that's up to the mod developer to fix
