### ISSUE TITLE
I cant compile my project!

### ISSUE THREAD

**Issue by ivan-hask** [Nbc66/source-sdk-2013-ce#6]
![image](https://user-images.githubusercontent.com/54760834/102709038-e302ec00-42b7-11eb-83e8-175deb714092.png)
every compile i see these errors. I dont know what i should to do.

**Comment by Bitl** [comment]
Replace the lines in sentences.cpp that say 

`#ifdef SDK2013CE
		buf.GetString( token, sizeof( token ) );
	#else
		buf.GetString( token );
	#endif`
	
to

`buf.GetString( token );`

This was caused because buf.GetString does not have a second argument.

**Comment by GamerDude27** [comment]
This has now been fixed with the merge of PR #8
