### ISSUE TITLE
Choppy Animations In The MP Branch

### ISSUE THREAD

**Issue by Yushe** [Nbc66/source-sdk-2013-ce#9]
Valve for whatever reason removed the files and code that helps animations be smooth in the 2013 MP branch.

The missing files are:
```
/game/shared/hl2mp/hl2mp_playeranimstate.cpp
/game/shared/hl2mp/hl2mp_playeranimstate.h
```
Goldeneye source still has these files and I think 2007 builds of source do as well, I did try fixing this issue in my project but I'm honestly not knowledgable enough and I just ended up causing an assertion to return `ACT_INVALID`.

I hope you're able to fix this because it's a serious issue.

**Comment by piotrek94692** [comment]
I need this fixed too

**Comment by piotrek94692** [comment]
I have looked into it, and found [this](https://github.com/ValveSoftware/source-sdk-2013/issues/449).
The [mentioned fork](https://github.com/tonysergi/source-sdk-2013/commits/master) has this issue fixed, and it has some other nice fixes too, but I'm not sure if it will work with Source 2013 CE
